#!/usr/bin/python

import os
import sys
import glob
import errno

# Three is a Charm. Write a script of your choice.

path = os.getcwd() + "/../network/*"

files = glob.glob(path)
for name in sorted(files):
    with open(name) as f:
        for line in f.readlines():
            if (line[:4] == "# ->"):
                print("\033[1;32;40m ")
            elif (line[0] == '#'):
                print("\033[1;34;40m ")
            else:
                print("\033[1;31;40m ")
            sys.stdout.write(line[:-1])

path = os.getcwd() + "/../system/*"

files = glob.glob(path)
for name in sorted(files):
    with open(name) as f:
        for line in f.readlines():
            if (line[:4] == "# ->"):
                print("\033[1;32;40m ")
            elif (line[0] == '#'):
                print("\033[1;34;40m ")
            else:
                print("\033[1;31;40m ")
            sys.stdout.write(line[:-1])

path = os.getcwd() + "/../scripts/*"

files = glob.glob(path)
for name in sorted(files):
    with open(name) as f:
        for line in f.readlines():
            if (line[:4] == "# ->"):
                print("\033[1;32;40m ")
            elif (line[0] == '#'):
                print("\033[1;34;40m ")
            else:
                print("\033[1;31;40m ")
            sys.stdout.write(line[:-1])
